### PR TITLE
Fixed a lot of issues with python code standards

### PR DESCRIPTION
**Pull request by Code-Done-Right**
I didn't make many technical changes, just cosmetic changes and add comments. Also, please read some of the comments in `tag.py` and `levels.py` please

### CODE REVIEW

**Comment by VG08** [comment]
Hey great work

**Comment by VG08** [comment]
so firstly uvloop is a tool that can make ur hikari code faster but only on non windows computers

**Comment by VG08** [comment]
then just ignore the levels.py file for now(forgot to tell this earlier) that shit is just messed up

**Comment by VG08** [comment]
so I'd say revert the changes in levels.py and I will fix it + transfer the modmail system to sqlite3
thanks for this work

**Comment by VG08** [comment]
Also as of now a lot of stuff in it is hardcoded to be guild specific so I am also gonna work on fixing that

**Comment by VG08** [comment]
I migrated modmail from json to sqlite, umm could you remove the comments from levels.py , that is really messed up I will fix later

**Comment by kotayashwin** [comment]
will send an updated pr

**Pull request closed without merging**
